### PR TITLE
Reorganized the chapters in the PHP handbook

### LINKED ISSUE #93: Restructuring the PHP coding standards
## Introduction

Given that the [PER coding styles](https://github.com/php-fig/per-coding-style/releases/tag/1.0.0) were released 8 days ago, and we've made progress in updating the coding standards a bit in the last few months - markdown updates, update some phrasing, removed outdated references, updated examples  (still pending in PR #92), I thought that it wouldn't be a bad idea to give some proper structure to the PHP WordPress Coding Standards (PHP WPCS).

By structure, I mean grouping the currently disjointed parts of the CS into some logical groups, like what PER standards (which are just PSR-12 standards at the moment) are doing.

## Current status

Currently, we have the following sections

```md
Single and Double Quotes
Indentation
Brace Style
Use `elseif`, not `else if`
Declaring Arrays
Closures (Anonymous Functions)
Multiline Function Calls
Regular Expressions
Opening and Closing PHP Tags
No Shorthand PHP Tags
Remove Trailing Spaces
Space Usage
Formatting SQL statements
Database Queries
Naming Conventions
Only one object structure (class/interface/trait) per file
Self-Explanatory Flag Values for Function Arguments
Interpolation for Naming Dynamic Hooks
Ternary Operator
Yoda Conditions
Clever Code
Error Control Operator `@`
Don't `extract()`
```

The PER style has the following main sections:

```md
Overview
General
Declare Statements, Namespace, and Import Statements
Classes, Properties, and Methods
Control Structures
Operators
Closures
Anonymous Classes
```

With subsections it looks like this:

```md
2. General
  2.1 Basic Coding Standard
  2.2 Files
  2.3 Lines
  2.4 Indenting
  2.5 Keywords and Types
3. Declare Statements, Namespace, and Import Statements
4. Classes, Properties, and Methods
  4.1 Extends and Implements
  4.2 Using traits
  4.3 Properties and Constants
  4.4 Methods and Functions
  4.5 Method and Function Arguments
  4.6 abstract, final, and static
  4.7 Method and Function Calls
5. Control Structures
  5.1 if, elseif, else
  5.2 switch, case
  5.3 while, do while
  5.4 for
  5.5 foreach
  5.6 try, catch, finally
6. Operators
  6.1. Unary operators
  6.2. Binary operators
  6.3. Ternary operators
7. Closures
8. Anonymous Classes
```

which is a lot more structured and clear in my opinion.

## Proposal

The proposal is to have the following grouping in the PHP WPCS:

```md
General
  Opening and Closing PHP Tags
  No Shorthand PHP Tags
  Brace Style
  Single and Double Quotes
  Multiline Function Calls

Naming and declarations
  Naming Conventions
  Interpolation for Naming Dynamic Hooks
  Declaring Arrays

Control structures
  Use `elseif`, not `else if`

Whitespace
  Space Usage
  Indentation
  Remove Trailing Spaces

Object-oriented programming
  Only one object structure (class/interface/trait) per file

Operators
  Ternary Operator

Database
  Database Queries
  Formatting SQL statements

Closures (Anonymous Functions)

Best recommendations
  Regular Expressions
  Self-Explanatory Flag Values for Function Arguments
  Clever Code
  Yoda Conditions
  Error Control Operator `@`
  Don't `extract()`
```

This will give a better structure - knowing where things should be located will help find what you need quickly, as well as prepare for the addition of more modern PHP constructs defined in the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/).

The content inside the existing standards **will stay the same**, so this is just a grouping change (adding new chapters and putting the other parts inside correct chapters).

Please let me know if you think that some sections belong in other chapters, or if you think that the chapters themselves need a better name.

CC @GaryJones @ntwb @jrfnl

### PR DESCRIPTION
**Pull request by dingo-d**
Closes #93 

Grouped similar chapters in a logical structure.

Reviewing this from a code comparison view might be... challenging.

I recommend just opening the new structure and the old one and comparing if everything was copied over correctly.

The proposed chapter grouping is the following:

~~~text
General
  Opening and Closing PHP Tags
  No Shorthand PHP Tags
  Single and Double Quotes

Naming
  Naming Conventions
  Interpolation for Naming Dynamic Hooks

Whitespace
  Space Usage
  Indentation
  Remove Trailing Spaces

Formatting
  Brace Style
  Declaring Arrays
  Multiline Function Calls

Object-Oriented Programming
  Only One Object Structure (Class/Interface/Trait) per File

Control Structures
  Use `elseif`, Not `else if`
  Yoda Conditions

Operators
  Ternary Operator
  Error Control Operator `@`

Database
  Database Queries
  Formatting SQL Statements

Recommendations
  Self-Explanatory Flag Values for Function Arguments
  Clever Code
  Closures (Anonymous Functions)
  Regular Expressions
  Don't `extract()`
~~~

### CODE REVIEW

**Review by jrfnl — APPROVED** [review]
I've verified this in detail and can confirm this complies with what the PR intends to do and no other textual changes have been made.

Only remark I have is that there are trailing spaces in two places in the file, which should probably be removed (line 358 and line 446).

**Comment by dingo-d** [comment]
@jrfnl I'm looking at the changes, but cannot see the trailing spaces in my editor.

**Comment by jrfnl** [comment]
> @jrfnl I'm looking at the changes, but cannot see the trailing spaces in my editor.

Your editor may have removed them, try saving and seeing if there is a diff (and make sure that whitespace is not being ignored for the diff).

image
image

**Comment by dingo-d** [comment]
Indeed, my PhpStorm didn't show them, but Sublime did 😅  

Thanks for catching it!

**Review by jrfnl — APPROVED** [review]
All good (@dingo-d You can fix up things like this in the original commit)

**Comment by dingo-d** [comment]
Just a note for other maintainers, please don't merge this until #92 has been merged. It's going to be easier to fixup this PR than vice versa

**Comment by dingo-d** [comment]
I've rebased the PR so that the code examples are pulled from the master branch.

I've found 2 grammar issues (?) that I've replaced:

> even when using a different _code style_, we recommend you still adhere to the WordPress Coding Standards with regards to these best practices.

with 

> even when using a different _code style_, we recommend you still adhere to the WordPress Coding Standards in regard to these best practices.

_with regards to_ -> _in regard to_

And 

> consider whether it can be broken into two or more shorter blocks, functions, or methods

with 

> consider whether it can be broken into two or shorter blocks, functions, or methods

Removed the unnecessary _more_ word.

If you have any objections to these two changes I can revert them, but they are really minor.

Other than that, no content has been changed.

**Comment by jrfnl** [comment]
> And
> 
> > consider whether it can be broken into two or more shorter blocks, functions, or methods
> 
> with
> 
> > consider whether it can be broken into two or shorter blocks, functions, or methods

I don't think this is correct as it changes the meaning of the sentence.

Adding a comma might be better ? But if I'm honest, I think the original sentence is correct and the grammar check wrong 😝 

> consider whether it can be broken into two or more, shorter blocks, functions, or methods

**Comment by dingo-d** [comment]
Now that I read it, it does make more sense to leave it as is instead of removing the `more`. 

I blame PhpStorm's grammar checker 😅 

Will revert it.

The first sentence does need a singular regard, so I'll leave this change 🙂

**Comment by dingo-d** [comment]
@GaryJones  @ntwb can you take a look?

**Review by GaryJones — APPROVED** [review]
In terms of ordering, then ✅ - so long as the content is on the page, I don't think it matters too much what order it's in, and if there's some value in aligning with a PSR/external standards, go for it.

**Pull request merged**
