### PR TITLE
Update css.md - correct grammar error

### PR DESCRIPTION
**Pull request by adeleke-akinade**
Corrects grammar error.

### CODE REVIEW

**Review by jrfnl — COMMENTED** [review]
Thanks for the PR. In my opinion, only the change on line 100 has merit. The other changes are not fixing typos nor grammatical errors.

**Comment by adeleke-akinade** [comment]
You're welcome.

Regarding the first change: "from core code to themes to plugins" to "from core code to themes and plugins". I think the latter reads nicer. However, that may be down to opinion.

Regarding the second change: "Just as CSS is evolving, so our standards will evolve with it" sounds incorrect to me. What is the purpose of the word "so" here?

**Review by jrfnl — APPROVED** [review]
Thanks for working with me to get this merge ready @adeleke-akinade !

**Comment by adeleke-akinade** [comment]
You're very welcome @jrfnl

**Comment by adeleke-akinade** [comment]
@jrfnl is it ready to merge now?

**Review by dingo-d — APPROVED** [review]

**Pull request merged**
